# 14 - PROJECT DEPLOY NEXUS - PART 1
---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
    - name: Untar nexus installer
      unarchive:
        src: /opt/nexus-3.59.0-01-unix.tar.gz
        dest: /opt/
        remote_src: yes


---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}} # variable that stores the result of the download_result
    - name: Untar nexus installer
      unarchive:
        src: {{download_result.dest}}
        dest: /opt/
        remote_src: yes  

---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes        

# 14 - PROJECT DEPLOY NEXUS - PART 1 - find module              
---    
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - debug: msg={{find_result}} #for us to see the result, we print it out
          #- name: Rename nexus folder
          #shell: mv   

---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path              

# 14 - PROJECT DEPLOY NEXUS - PART 1 - conditional
---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path      
      when: not stat_result.stat.exists #execute this, only if the folder does not exist     



---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path      
      when: not stat_result.stat.exists #execute this, only if the folder does not exist

- name: create nexus user to own nexus folder
  hosts: 67.205.137.130
  tasks:
    - name: create nexus group or ensure group nexus exist
      group:                                                                              
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

#   15 - Project Deploy Nexus - Part 2 - blockinfile
---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path      
      when: not stat_result.stat.exists #execute this, only if the folder does not exist
- name: create nexus user to own nexus folder
  hosts: 67.205.137.130
  tasks:
    - name: create nexus group or ensure group nexus exist
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: 67.205.137.130
  tasks:
    - name: Set run_as_user nexus
      blockinfile:
        path: /opt/nexus/bin/nexus.rc
        block: |
          run_as_user="nexus"


#   15 - Project Deploy Nexus - Part 2 - lineinfile
---
- name: install java and net-tools
  hosts: 67.205.137.130
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: 67.205.137.130
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path      
      when: not stat_result.stat.exists #execute this, only if the folder does not exist

- name: create nexus user to own nexus folder
  hosts: 67.205.137.130
  tasks:
    - name: create nexus group or ensure group nexus exist
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: 67.205.137.130
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
                                
#   15 - Project Deploy Nexus - Part 2 - 

---
- name: install java and net-tools
  hosts: nexus_server
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: nexus_server
  tasks:
    - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists #only execute untar when there is no /opt/nexus folder    
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path      
      when: not stat_result.stat.exists #execute this, only if the folder does not exist 

- name: create nexus user to own nexus folder
  hosts: nexus_server
  tasks:
    - name: create nexus group or ensure group nexus exist
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: nexus_server
  become: True
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start


#   15 - Project Deploy Nexus - Part 2 - verify nexus is running

---
- name: install java and net-tools
  hosts: nexus_server
  tasks:
    - name: Update apt repos and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and install Nexus Installer
  hosts: nexus_server
  tasks:
    - name: Check nexus folder stat
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists #only execute untar when there is no /opt/nexus folder    
    - name: find nexus folder
      find:
        path: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result #save the result of the find module inside the find_result variable
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus #rename it to nexus, we need to specify the full path      
      when: not stat_result.stat.exists #execute this, only if the folder does not exist  

- name: create nexus user to own nexus folder
  hosts: nexus_server
  tasks:
    - name: create nexus group or ensure group nexus exist
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: nexus_server
  become: True
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

- name: Verify nexus is running
  hosts: nexus_server
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: wait one minute  #for the play to wait until port open on the host before executing the netstat command
      pause:
        minutes: 1
    - name: Check with netstat
      shell: netstat -lnpt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}    